/**
 * @libar-docs
 * @libar-docs-status roadmap
 * @libar-docs-implements EnhancedIndexGeneration
 * @libar-docs-target src/renderable/codecs/index-codec.ts
 *
 * ## IndexCodecOptions — DD-1, DD-5 Decisions
 *
 * **Decision DD-1 (New IndexCodec vs extend existing):** Create a new IndexCodec
 * registered in CodecRegistry, NOT a standalone generator or extension of the
 * current docs-live/INDEX.md (which is a static file, not generated by any code).
 *
 * **Rationale (DD-1):** The index needs MasterDataset pre-computed views
 * (`byProductArea`, `byPhase`, `byStatus`, `byCategory`) to generate statistics.
 * Only codecs registered in CodecRegistry receive MasterDataset via the
 * `codec.decode(dataset)` pipeline. A standalone generator (like
 * ProcessApiReferenceGenerator) would need to wire its own MasterDataset access,
 * duplicating what CodecBasedGenerator already provides. The codec approach also
 * gets free integration with `generateDocument('index', dataset)`,
 * `generateAllDocuments()`, and the `CodecOptions` type-safe options pipeline.
 *
 * **Decision DD-5 (ReferenceDocConfig vs standalone codec):** Use a standalone
 * IndexCodec rather than a ReferenceDocConfig entry. The IndexCodec is registered
 * directly in CodecRegistry as document type `'index'`, not routed through the
 * reference codec's 4-layer composition pipeline.
 *
 * **Rationale (DD-5):** ReferenceDocConfig's 4-layer composition (conventions,
 * diagrams, shapes, behaviors) is designed for scoped reference documents that
 * assemble content from annotated sources. The index document is fundamentally
 * different — it is a NAVIGATION document that lists OTHER documents, computes
 * cross-cutting statistics from MasterDataset views, and composes them with
 * editorial preamble sections. None of the 4 layers apply:
 * - No convention tags to extract (the index doesn't document conventions)
 * - No scoped diagrams (the index doesn't visualize architecture)
 * - No TypeScript shapes (the index doesn't expose API surfaces)
 * - No behavior categories (the index doesn't describe behaviors)
 *
 * However, the IndexCodec DOES reuse the `preamble` concept from
 * ReferenceDocConfig — editorial `SectionBlock[]` prepended before generated
 * content. This is passed via `IndexCodecOptions.preamble`, not via
 * ReferenceDocConfig. The preamble mechanism is a pattern, not a type coupling.
 *
 * ### Integration Points
 *
 * | Integration | How |
 * |-------------|-----|
 * | CodecRegistry | `CodecRegistry.register('index', IndexCodec)` |
 * | DOCUMENT_TYPES | Add `index: { outputPath: 'INDEX.md', description: '...' }` |
 * | CodecOptions | Add `index?: IndexCodecOptions` to CodecOptions interface |
 * | delivery-process.config.ts | Add `generatorOverrides.index.outputDirectory: 'docs-live'` |
 * | generateAllDocuments() | Automatically included via DOCUMENT_TYPES iteration |
 */

import type { SectionBlock } from '../../src/renderable/schema.js';
import type { BaseCodecOptions } from '../../src/renderable/codecs/types/base.js';

// ---------------------------------------------------------------------------
// IndexCodecOptions
// ---------------------------------------------------------------------------

/**
 * Options for the IndexCodec.
 *
 * Controls which sections appear in the generated index and provides
 * the editorial preamble content (audience reading paths, document
 * roles matrix, quick finder table).
 *
 * The codec composes two content types:
 * 1. **Auto-generated** — Statistics and document listings from MasterDataset
 * 2. **Editorial** — Preamble sections authored in config
 *
 * This separation follows the same principle as ReferenceDocConfig.preamble
 * but is specific to the index document's navigation-focused structure.
 */
export interface IndexCodecOptions extends BaseCodecOptions {
  // ─── Editorial Preamble ──────────────────────────────────────────────────

  /**
   * Static preamble sections prepended before all generated content.
   *
   * Expected to contain:
   * - Quick navigation table (If you want X, read Y)
   * - Audience reading paths (New User, Developer/AI, Team Lead/CI)
   * - Document roles matrix (Audience x Document x Focus)
   * - Key concepts glossary
   *
   * These sections require editorial judgment and cannot be derived
   * from MasterDataset metadata.
   */
  readonly preamble?: readonly SectionBlock[];

  // ─── Section Visibility Toggles ──────────────────────────────────────────

  /** Include product area statistics table (default: true) */
  readonly includeProductAreaStats?: boolean;

  /** Include phase progress summary with completion percentage (default: true) */
  readonly includePhaseProgress?: boolean;

  /** Include unified document inventory table (default: true) */
  readonly includeDocumentInventory?: boolean;

  /** Include package metadata header (default: true) */
  readonly includePackageMetadata?: boolean;

  // ─── Document Inventory Configuration ────────────────────────────────────

  /**
   * Document entries for the unified inventory.
   *
   * Each entry describes a document from either docs/ or docs-live/.
   * The codec merges these with any auto-discovered generated documents
   * from MasterDataset to produce a single unified listing.
   *
   * Documents are organized by topic, NOT by source directory.
   * The reader should not need to know whether a document is manual
   * or generated.
   */
  readonly documentEntries?: readonly DocumentEntry[];
}

/**
 * A document entry for the unified inventory.
 *
 * Describes a single document in the navigation index.
 * Used for both manual docs/ and generated docs-live/ documents.
 */
export interface DocumentEntry {
  /** Document title (e.g., "Architecture Overview") */
  readonly title: string;

  /** Relative path from project root (e.g., "docs/ARCHITECTURE.md" or "docs-live/PRODUCT-AREAS.md") */
  readonly path: string;

  /** Brief description of what the document covers */
  readonly description: string;

  /** Primary audience for this document */
  readonly audience: 'Everyone' | 'Developers' | 'AI/Devs' | 'Users' | 'Writers' | 'Team Leads' | 'CI/CD' | 'Maintainers' | 'Reference';

  /**
   * Topic category for grouping in the index.
   * Documents with the same topic appear in the same section.
   */
  readonly topic: string;
}

// ---------------------------------------------------------------------------
// Default Options
// ---------------------------------------------------------------------------

/**
 * Default options for IndexCodec.
 *
 * All auto-generated sections are enabled by default.
 * Preamble and document entries are empty by default — they must be
 * provided via delivery-process.config.ts.
 */
export const DEFAULT_INDEX_OPTIONS: Required<Omit<IndexCodecOptions, 'preamble' | 'documentEntries' | 'limits'>> & {
  preamble: readonly SectionBlock[];
  documentEntries: readonly DocumentEntry[];
} = {
  generateDetailFiles: false,
  detailLevel: 'detailed',
  includeProductAreaStats: true,
  includePhaseProgress: true,
  includeDocumentInventory: true,
  includePackageMetadata: true,
  preamble: [],
  documentEntries: [],
};

export function _indexCodecOptionsPlaceholder(): never {
  throw new Error('EnhancedIndexGeneration not yet implemented - roadmap pattern');
}
