export {
  MaturityValueSchema,
  ProjectionFilterSchema,
  StatusValueSchema,
  filterPattern,
  filterPatterns,
} from './_shared/filter.js';
export type { ProjectionFilter } from './_shared/filter.js';
export {
  projectArchitectureComparison,
  projectBoundedContext,
  projectArchitectureGraph,
  ArchitectureGraphSchema,
  projectArchitectureNeighborhood,
  projectDependencyEdges,
  parseAndProjectDependencyContext,
  projectDependencyContext,
  BundleIncludeSchema,
  BundleModeSchema,
  parseAndProjectPatternBundle,
  PatternBundleOptionsSchema,
  OpenQuestionListOptionsSchema,
  parseAndProjectOpenQuestionList,
  projectOpenQuestionList,
  projectOrphanPatternList,
  parseAndProjectPatternCatalog,
  projectPatternBundle,
  projectPatternCatalog,
  projectPatternDetail,
  projectPatternSummary,
} from './pattern-relations/index.js';
export { ProjectionError } from './errors.js';
export type { ProjectionErrorCode } from './errors.js';
export {
  projectCurrentWork,
  projectRoadmapTimeline,
  projectChangelog,
  projectStatusDistribution,
  projectTraceabilityMatrix,
} from './delivery-reporting/index.js';
export {
  collectBusinessRuleProductAreas,
  projectBusinessRule,
  parseAndProjectBusinessRuleSet,
  projectBusinessRuleSet,
  projectDecisionCatalog,
  projectDecisionRecord,
  TaxonomyDigestOptionsSchema,
  parseAndProjectTaxonomyDigest,
  projectTaxonomyDigest,
  summarizeTaxonomyDigest,
  projectValidationRuleDigest,
} from './governance/index.js';
export {
  projectDeliverable,
  projectDeliverableManifest,
  parseAndProjectFileReadingList,
  projectFileReadingList,
  parseAndProjectHandoffRecord,
  projectHandoffRecord,
  parseAndProjectScopeReadinessReport,
  projectScopeReadinessReport,
  parseAndProjectSessionContext,
  projectSessionContextBundle,
} from './execution-context/index.js';
export {
  projectAnnotationCoverage,
  projectOverviewDigest,
  projectRequirementDigest,
  projectRequirementExecutableDigest,
  projectRequirementSpecsDigest,
  projectRoleProfile,
  projectRoleProfiles,
  projectSourceInventoryDigest,
  projectTagUsage,
} from './operational-insights/index.js';
export {
  SupportedDocumentationTypeRegistryEntrySchema,
  SUPPORTED_DOCUMENTATION_TYPE_REGISTRY,
  SUPPORTED_DOCUMENTATION_TYPES,
  getDocumentationTypeMetadata,
  getSupportedDocumentationTypeMetadata,
  resolveProjectionFilter,
  parseAndProjectArchitectureDiagram,
  ProjectConfigOptionsSchema,
  SourceGlobGroupsSchema,
  parseAndProjectConfig,
  ProjectDocumentationBundleOptionsSchema,
  parseAndProjectDocumentationBundle,
  parseAndProjectPrChangeReview,
  assertGeneratorNotDegenerate,
  GeneratorDegenerateError,
  projectTaxonomyEmbeddedShapes,
  taxonomyGroupSource,
  TAXONOMY_EMBEDDED_GENERATORS,
  TAXONOMY_ROLE_ENUM_SOURCE,
  TAXONOMY_SKILL_GENERATOR,
  TAXONOMY_TAG_COUNT_SOURCE,
} from './documentation-composition/index.js';
export type {
  PatternBundleOptions,
  DepContextOptions,
  OpenQuestionListOptions,
  PatternCatalogOptions,
  ArchitectureGraph,
} from './pattern-relations/index.js';
export type {
  BusinessRuleSetOptions,
  TaxonomyDigestCountSummary,
  TaxonomyDigestOptions,
} from './governance/index.js';
export type {
  FileReadingListOptions,
  HandoffOptions,
  ScopeReadinessOptions,
  SessionContextOptions,
} from './execution-context/index.js';
export type {
  ProjectArchitectureDiagramOptions,
  ProjectDocumentationBundleOptions,
  ProjectConfigOptions,
  ProjectPrChangeReviewOptions,
  SourceGlobGroups,
  DocumentationTypeMetadata,
  SupportedDocumentationTypeRegistryEntry,
  SupportedDocumentationType,
  SupportedDocumentationTypeMetadata,
  TaxonomyEmbeddedGeneratorInfo,
  TaxonomyEmbeddedShape,
} from './documentation-composition/index.js';
